batch_size: 2048
epochs: 8000
log_every: 100
eval_every: 1
n_workers: 16
fp16: True
accumulate_grad_batches: 1
normalize_z: False

fine_tune_from:

std_margin: 1

optimizer: sgd
wd: 5e-4
lr: 5e-2

scheduler: multistep
#warmup_epochs: 50
milestones: [1600, 2400, 3200]
gamma: 0.1

dataset:
  name: cifar100
  n_classes: 100
  size: 32
  path:
  aug_policy: cifar

encoder_type: resnet
encoder:
  backbone: resnet50
  out_dim:
  small_kernel: True

clip:
  model_name: ViT-B-16
  pretrained: laion400m_e32

teacher_path: ./lightning_logs/cifar100_vitb16_2_layer_classifier_sgd_cifar_aug/clip_ViT-B-16_2_layer_classifier_best_175.pth

comment: cifar100_clip_supervised_VIT-B-16_d_corr_distil_classifier_clip_orig_label_dcorr_multistep_10_bs_2048
